function trytoplotsinusoid

time = 0;
dt=0.001;
frequency = 200;
hfig = figure('Position', [300 300 900 650], 'Resize', 'off');
movegui(hfig,'center');

% initiate timer for animation
uicontrol('Style', 'pushbutton',...
           'String', 'Start',...
           'Position', [20 10 100 30],...
           'Callback', @startbutton);
uicontrol('Style', 'pushbutton',...
           'String', 'Stop',...
           'Position', [120 10 100 30],...
           'Callback', @stopbutton);
%--------------------------------------------------------------------------       
uicontrol('Style', 'text', ...
           'String', 'Quelle 1',...
           'Position', [750 550 150 20],...
           'BackgroundColor', [0 0.4 0.6]);
uicontrol('Style', 'text', ...
           'String', 'Freq[Hz]',...
           'Position', [750 520 75 20],...
           'BackgroundColor', [0.6 0.8 0.8]);
uicontrol('Style', 'edit', ...
           'String', 'Frequenz',...
           'Position', [825 520 75 20]);
uicontrol('Style', 'text', ...
           'String', 'Amplitude',...
           'Position', [750 490 75 20],...
           'BackgroundColor', [0.6 0.8 0.8]);       
uicontrol('Style', 'edit', ...
           'String', 'Amplitude',...
           'Position', [825 490 75 20]);
uicontrol('Style', 'text', ...
           'String', 'Phase[rad]',...
           'Position', [750 460 75 20],...
           'BackgroundColor', [0.6 0.8 0.8]);
uicontrol('Style', 'edit', ...
           'String', 'Phase',...
           'Position', [825 460 75 20]);
       
uicontrol('Style', 'text', ...
           'String', 'Quelle 2',...
           'Position', [750 420 150 20],...
           'Callback', @stopbutton);
uicontrol('Style', 'text', ...
           'String', 'Freq[Hz]',...
           'Position', [750 390 75 20]);
uicontrol('Style', 'edit', ...
           'String', 'Frequenz',...
           'Position', [825 390 75 20]);
uicontrol('Style', 'text', ...
           'String', 'Amplitude',...
           'Position', [750 360 75 20]);       
uicontrol('Style', 'edit', ...
           'String', 'Amplitude',...
           'Position', [825 360 75 20]);
uicontrol('Style', 'text', ...
           'String', 'Phase[rad]',...
           'Position', [750 330 75 20]);
uicontrol('Style', 'edit', ...
           'String', 'Phase',...
           'Position', [825 330 75 20]);       
       
       
uicontrol('Style', 'text', ...
           'String', 'Quelle 3',...
           'Position', [750 290 150 20],...
           'Callback', @stopbutton);
uicontrol('Style', 'text', ...
           'String', 'Freq[Hz]',...
           'Position', [750 260 75 20]);
uicontrol('Style', 'edit', ...
           'String', 'Frequenz',...
           'Position', [825 260 75 20]);
uicontrol('Style', 'text', ...
           'String', 'Amplitude',...
           'Position', [750 230 75 20]);       
uicontrol('Style', 'edit', ...
           'String', 'Amplitude',...
           'Position', [825 230 75 20]);
uicontrol('Style', 'text', ...
           'String', 'Phase[rad]',...
           'Position', [750 200 75 20]);
uicontrol('Style', 'edit', ...
           'String', 'Phase',...
           'Position', [825 200 75 20]);       
        
        

    t = timer('Period',dt,'TimerFcn', @plotSinusoid,...
    'ExecutionMode','FixedRate', 'TasksToExecute',Inf);    
        
    function startbutton(handle, event)
        t = timer('Period',dt,'TimerFcn', @plotSinusoid,...
        'ExecutionMode','FixedRate', 'TasksToExecute',Inf);
        start(t);
    end


    function stopbutton(handle, event)

        stop(timerfindall);delete(timerfindall);
    end


function plotSinusoid( handle, event )
%UNTITLED Summary of this function goes here
  %Detailed explanation goes here

time=time+dt;
[X,Y] = meshgrid(-20:.25: 20);
c=343;
amplitude=1;
T=1/frequency;
lambda = c/frequency;
r = sqrt(X.^2 + Y.^2);
Z = amplitude*sin(2*pi*(time./T-r/lambda));
surf(X,Y,Z); %'LineStyle,'none', 'EdgeColor','none'
axis off;
shading(gca, 'interp');
view(2)
colormap('Gray');
drawnow;
end

end